In [1]:
import numpy as np
np.random.seed(0)


def exercise_1():
    # What is the resulting array’s dimension of the addition of two arrays of dimension
    # (1,2,3) and (5,2,1). Use the broadcasting rules covered in the lecture to analyze the
    # problem.
    print("Exercise 1:\n")

    print("The resulting shape is (5, 2, 3) The broadcasting rule will pad the one with fewer dimensions with ones on "
          "its left side.\n")

    # What if the two arrays are of dimension of (4,4) and (1,2,4)?
    print("It can not be broadcasted because the shapes don't match.\n")


def exercise_2():
    print("Exercise 2:\n")

    #  Create an array containing the values 1–15
    #  , reshape it into a 3-by-5 array, then use
    new_array = np.arange(1, 15 + 1, 1).reshape((3, 5))
    print(new_array)
    # indexing and slicing techniques to perform each of the following operations:
    # a. Select row2.
    print("Row 2:\n", new_array[2])
    # b. Select column 4.
    print("Column 4:\n", new_array[:, 4])
    # c. Select rows 0 and 1.
    print("Rows 0 an 1:\n", new_array[:2])

    # d. Select columns 2-4.
    print("Columns 2-4:\n", new_array[:, 2:5])

    # e.Select the element that is in row 1 and column 4.
    print("Row 1, Column 4:\n", new_array[1, 4])

    # f. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.
    print("All From Row 1 and Row 2, Columns 0, 2 and 4:\n",
          new_array[0:2, [0, 2, 4]])


def exercise_3():
    print("Exercise 3:\n")

    # Create the two-dimensional arrays
    array1 = np.array([[0, 1], [2, 3]])
    array2 = np.array([[4, 5], [6, 7]])
    # a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top
    # of array2.
    array3 = np.vstack([array2, array1])
    print("Array3: \n", array3, "\n")
    # b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right
    # of array1.
    array4 = np.hstack([array1, array2])
    print("Array4: \n", array4, "\n")
    # c) Use vertical stacking with two copies of array 4 to create a 4-by-4 array5.
    array5 = np.vstack([array4, array4])
    print("Array5: \n", array5, "\n")
    # d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
    array6 = np.hstack([array3, array3])
    print("Array6: \n", array6, "\n")


def exercise_4():
    print("Exercise 4:\n")

    # Use concatenate method in NumPy to reimplement the tasks in the previous
    # question.
    # Create the two-dimensional arrays
    array1 = np.array([[0, 1], [2, 3]])
    array2 = np.array([[4, 5], [6, 7]])
    # a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top
    # of array2.
    array3 = np.concatenate([array2, array1])
    print("Array3: \n", array3, "\n")
    # b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right
    # of array1.
    array4 = np.concatenate([array1, array2], axis=1)
    print("Array4: \n", array4, "\n")
    # c) Use vertical stacking with two copies of array 4 to create a 4-by-4 array5.
    array5 = np.concatenate([array4, array4])
    print("Array5: \n", array5, "\n")
    # d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
    array6 = np.concatenate([array3, array3], axis=1)
    print("Array6: \n", array6, "\n")


def exercise_5():
    print("Exercise 5:\n")
    # Generate a 15-by-15 random array, call it array1, with each element an integer
    # between 1 to 10 uniformly sampled (both 1 and 10 are included).
    # Generate an array, called
    # array2, that includes all values greater than 8 in the random array1 efficiently, without using
    # the loop. Also, check how many elements are in array2?
    array1 = np.random.randint(1, 10, size=(3, 3))  # Return random integers from the “discrete uniform” distribution
    print(array1)
    array2 = array1[array1 > 5]
    print("Array2: \n", array2)
    print("Array2's size: ", array2.size)


def main():
    exercise_1()
    exercise_2()
    exercise_3()
    exercise_4()
    exercise_5()


# (3 pts) What is the resulting array’s dimension of the addition of two arrays of dimension
# (1,2,3) and (5,2,1). Use the broadcasting rules covered in the lecture to analyze the
# problem. What if the two arrays are of dimension of (4,4) and (1,2,4)?


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    main()


Exercise 1:

The resulting shape is (5, 2, 3) The broadcasting rule will pad the one with fewer dimensions with ones on its left side.

It can not be broadcasted because the shapes don't match.

Exercise 2:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Row 2:
 [11 12 13 14 15]
Column 4:
 [ 5 10 15]
Rows 0 an 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Columns 2-4:
 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
Row 1, Column 4:
 10
All From Row 1 and Row 2, Columns 0, 2 and 4:
 [[ 1  3  5]
 [ 6  8 10]]
Exercise 3:

Array3: 
 [[4 5]
 [6 7]
 [0 1]
 [2 3]] 

Array4: 
 [[0 1 4 5]
 [2 3 6 7]] 

Array5: 
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]] 

Array6: 
 [[4 5 4 5]
 [6 7 6 7]
 [0 1 0 1]
 [2 3 2 3]] 

Exercise 4:

Array3: 
 [[4 5]
 [6 7]
 [0 1]
 [2 3]] 

Array4: 
 [[0 1 4 5]
 [2 3 6 7]] 

Array5: 
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]] 

Array6: 
 [[4 5 4 5]
 [6 7 6 7]
 [0 1 0 1]
 [2 3 2 3]] 

Exercise 5:

[[6 1 4]
 [4 8 4]
 [6 3 5]]
Array2: 
 [6 8 6]
Array2's size:  3
